create table BOOK(
    CODE VARCHAR(16) PRIMARY KEY,
    AUTHOR VARCHAR(16),
    STATUS INT,
    PAGE_COUNT INT,
    CHAPTER_COUNT INT,
    TITLE VARCHAR(128),
    COVER VARCHAR(256),
    INTRO VARCHAR(1024),
    CREATE_TIME TIMESTAMP,
    PUBLISH_TIME TIMESTAMP
)