CREATE VIEW COMMENT_VIEW(CODE, CONTENT, TARGET, REPLY_TO, TYPE, CREATE_TIME, AUTHOR, RECEIVER, AUTHOR_NAME, AUTHOR_PORTRAIT, RECEIVER_NAME) AS
SELECT C.CODE, C.CONTENT, C.TARGET, C.REPLY_TO, C.TYPE, C.CREATE_TIME, C.AUTHOR, C.RECEIVER, AP.NAME, AP.PORTRAIT, RP.NAME
FROM COMMENT C
LEFT JOIN PROFILE AP ON C.AUTHOR = AP.CODE
LEFT JOIN PROFILE RP ON C.RECEIVER = RP.CODE